services:
  web-rake:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    command: >
      /bin/bash -c "
      git config --global user.email '${GIT_EMAIL}' &&
      git config --global user.name '${GIT_USER}' &&
      rake publish
      "
    container_name: web-rake
    image: web-rake
    volumes:
      - .:/web
    environment:
      - GIT_USER
      - GIT_EMAIL
      - GITHUB_TOKEN
