FROM ruby

# prepare a user which runs everything locally! - required in child images!
RUN useradd --user-group --create-home --shell /bin/false app

ENV HOME=/home/app
WORKDIR $HOME


# prepare a user which runs everything locally! - required in child images!
#RUN useradd --user-group --create-home --shell /bin/false app
ENV APP_NAME=web

# before switching to user we need to set permission properly
# copy all files, except the ignored files from .dockerignore
COPY . $HOME/$APP_NAME/

#RUN apt update \
# & gem install bundler \
# & bundle install

#COPY ./.docker/Rakefile $HOME/$APP_NAME/
RUN chown -R app:app $HOME/*

WORKDIR $HOME/$APP_NAME

RUN apt update && apt upgrade -y \
  && gem install bundler \
  && bundle update \
  && bundle install

USER app

#RUN rake publihs
CMD ["/bin/bash"]
