on:
  push:
    branches:
      - source
  pull_request:
    branches:
      - source

name: rake

env:
  cache-version: v3

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Set up Docker Compose
      - name: Set up Docker Compose
        uses: KengoTODA/actions-setup-docker-compose@v1
        with:
          version: '2.14.2'

      # Debug workspace (optional, for troubleshooting)
      - name: List Workspace Files
        run: ls -R

      # Run Docker Compose
      - name: Run Docker Compose
        run: docker-compose up
        env:
          GIT_USER: ${{ secrets.USER_GITHUB }}
          GIT_EMAIL: ${{ secrets.EMAIL_GITHUB }}
          # GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
