name: Publish Site

on:
  push:
    branches:
      - source

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      # Checkout the source code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up SSH keys for GitHub access
      - name: Set up Deploy Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          echo "Host github.com
            IdentityFile ~/.ssh/id_ed25519
            StrictHostKeyChecking no" > ~/.ssh/config

      # Install Ruby and Bundler
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
          bundler-cache: true

      # Install dependencies
      - name: Install Dependencies
        run: bundle install

      # Build the Jekyll site
      - name: Build Site
        run: bundle exec jekyll build

      # Push the generated site to the master branch
      - name: Publish Site to Master
        run: |
          cd _site
          git init
          git config user.name "${{ secrets.USER_GITHUB }}"
          git config user.email "${{ secrets.EMAIL_GITHUB }}"
          git add .
          git commit -m "Site updated at $(date -u)"
          git remote add origin git@github.com:mattocci27/mattocci27.github.io.git
          git push --force origin master
