on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

name: rake

env:
  cache-version: v3

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    container:
          image: ruby:3.0.2

    steps:
      - uses: actions/checkout@v1
      - run: gem install bundler --no-document
      - run: gem install rake
      - run: bundle config set deployment 'true'
      - run: bundle install --jobs 4 --retry 3
      - run: rake publish