on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

name: rake

env:
  cache-version: v3

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    container:
          image: ruby:3.0.2

    steps:
      - uses: actions/checkout@v1
      - run: git config --global user.email "mattocci27@gmail.com"
      - run: git config --global user.name "mattocci27"
      - run: gem install bundler --no-document
      - run: bundle config set deployment 'true'
      - run: bundle install --jobs 4 --retry 3
      - name: Push to main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          rake publish
          temp_dir=$(mktemp -d) \
          cp -rf _site/. $temp_dir \
          cd $temp_dir \
          git init \
          git add . \
          export COMMIT_TITLE="Site updated at $(date +"%Y-%m-%d %T UTC")"
          git commit -m "$COMMIT_TITLE"
          origin=https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com:mattocci27/mattocci27.github.io.git
          git push $origin dev2